# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.s3.endpoint: 'http://172.20.0.3:9000'
    app.s3.key: 'minio'
    app.s3.secret: 'minio123'
    app.s3.region: 'us-east-1'
    app.s3.version: 'latest'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    app.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -   version: '%app.s3.version%'
                region: '%app.s3.region%'
                path_style_endpoint: true
                endpoint: '%app.s3.endpoint%'
                use_path_style_endpoint: true
                credentials:
                    key: '%app.s3.key%'
                    secret: '%app.s3.secret%'


    League\Flysystem\FilesystemOperator $bugFilesystem:
        alias: oneup_flysystem.minio_fs_filesystem


