version: '3.8'
services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_php
    volumes:
      - ./backend:/var/www/html:delegated
      - ./backend/vendor:/var/www/html/vendor
    depends_on:
      - db
    environment:
      APP_ENV: dev
    networks:
      - appnet

  nginx:
    image: nginx:1.25
    container_name: app_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:ro
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - appnet

  db:
    image: postgres:15
    container_name: bug_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    networks:
      - appnet

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_front_node
    volumes:
      - ./frontend:/usr/src/app:delegated
    ports:
      - "3000:3000"
    networks:
      - appnet

  symfony_minio:
    image: quay.io/minio/minio
    container_name: symfony_minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    networks:
      - appnet

volumes:
  db_data:
  minio_data:

networks:
  appnet:
    driver: bridge
