%%{init: {'theme':'dark', 'themeVariables': { 'primaryColor': '#4CAF50', 'primaryTextColor': '#fff', 'primaryBorderColor': '#388E3C', 'lineColor': '#F57C00'}}}%%
xychart-beta
    title "Code Coverage by Directory"
    x-axis ["Application", "Domain", "Infrastructure", "Command", "Repository"]
    y-axis "Coverage %" 0 --> 100
    bar [100, 83.33, 4.35, 0, 0]
