%%{init: {'theme':'dark', 'themeVariables': { 'primaryColor': '#4CAF50', 'primaryTextColor': '#fff', 'primaryBorderColor': '#388E3C', 'lineColor': '#F57C00'}}}%%
xychart-beta
    title "Code Coverage by Directory"
    x-axis ["Application", "Infrastructure", "Domain"]
    y-axis "Coverage %" 0 --> 100
    bar [100, 90.45, 84]
