flysystem:
    storages:
        bug_storage:
            adapter: 'aws'
            options:
                client: 'aws_client'
                bucket: 'bug-images'

aws:
    clients:
        aws_client:
            service: 'aws.s3'
            region: 'us-east-1'
            endpoint: 'http://minio:9000'   # MinIO service name from docker-compose
            use_path_style_endpoint: true   # Required for MinIO
            credentials:
                key: 'minio'
                secret: 'minio123'
